# Generated by Django 4.0.6 on 2022-08-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphprefer',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
