# Generated by Django 4.0.6 on 2022-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Categroies'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='catagory',
            new_name='category',
        ),
    ]
