# Generated by Django 4.0.6 on 2022-07-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_catagory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
